version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000/tcp"
      - "5043:5043/tcp"
      - "12201:12201/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # redis:
  #   build:
  #     context: redis/
  #     args:
  #       REDIS_VERSION: $REDIS_VERSION
  #   volumes:
  #     - ./redis/config/:/usr/local/etc/redis/redis.conf:ro
  #   ports:
  #     - "6379:6379/tcp"
  #   networks:
  #     - elk

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601/tcp"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstashtest:
    build:
      context: test/
      args:
        HTTP_PROXY: $HTTP_PROXY
        HTTPS_PROXY: $HTTPS_PROXY
    ports:
      - "5045:5045/tcp"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        gelf-compression-type: "gzip"
        gelf-compression-level: "1"
    networks:
      - elk
    # depends_on:
    #   - elasticsearch
    #   - logstash
    #   - redis

  prometheus:
    build:
      context: prometheus/
      args:
        PROMETHEUS_VERSION: $PROMETHEUS_VERSION
    ports:
      - "9090:9090/tcp"
    networks:
      - elk
    depends_on:
      - logstashtest

networks:

  elk:
    driver: bridge
