version: '3.5'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    deploy:
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==linux
    volumes:
      - "//c/git/docker-elk/elasticsearch/config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: mylogstash
    deploy:
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==linux
    volumes:
      - "//c:/git/docker-elk/logstash/config/logstash.yml /usr/share/logstash/config/logstash.yml:ro"
      - "//c:/git/docker-elk/logstash/pipeline /usr/share/logstash/pipeline:ro"
    ports:
      - 5000:5000
      - 5043:5043
      - 12201:12201/udp
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # redis:
  #   image: redis
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role==worker
  #         - node.platform.os==linux
  #   volumes:
  #     - ./redis/config/:/usr/local/etc/redis/redis.conf:ro
  #   networks:
  #     - elk
  #   depends_on:
  #     - logstash

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:6.3.2
  #   deploy:
  #     mode: global
  #     placement:
  #       constraints:
  #         - node.role==worker
  #         - node.platform.os==linux
  #   volumes:
  #     - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - elk
  #   depends_on:
  #     - redis

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    deploy:
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==linux
    volumes:
      - "//c:/git/docker-elk/kibana/config/ /usr/share/kibana/config:ro"
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstashtest:
    image: logstashtest
    deploy:
      placement:
        constraints:
          - node.role==worker
          - node.platform.os==linux
    ports:
      - 5045:5045
    logging:
      driver: gelf
      options:
        gelf-address: "udp://logstash:12201"
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash
      # - redis

  # prometheus:
  #   image: prom/prometheus:v2.3.1
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - elk
  #   depends_on:
  #     - logstashtest

networks:
  elk:
